<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>MediaToolkit.NetCore</PackageId>
    <PackageDescription>MediaToolkit port to .Net Core</PackageDescription>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>MediaToolkit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MedallionShell" Version="1.6.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.0.9" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
</Project>
